# Generated by Django 3.1.3 on 2020-11-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Phone', models.IntegerField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('PhotoFileName', models.CharField(max_length=100)),
            ],
        ),
    ]
